// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtofvxatowwgnrtmpxap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0b2Z2eGF0b3d3Z25ydG1weGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjAzNTgsImV4cCI6MjA3MTE5NjM1OH0.MXLUL1weKqY1VTf-FMlV6xfejsxPOEanGnyJ4dNnXh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});